preserve_hierarchy: true

files:
  [
    {
      'source': '/messages/main/en-US/*.json',
      'translation': '/messages/main/%locale%/%original_file_name%',
    },
    {
      'source': '/messages/renderer/en-US/*.json',
      'translation': '/messages/renderer/%locale%/%original_file_name%',
    },
  ]
