preserve_hierarchy: true

files:
  [
    {
      'source': '/messages/en-US/*.json',
      'dest': '/desktop/%file_name%.json',
      'translation': '/messages/%locale%/%original_file_name%',
    },
  ]
