preserve_hierarchy: true

files:
  [
    {
      'source': '/messages/main/en-US/*.json',
      'translation': '/messages/main/%locale%/%original_file_name%',
      'exclude_target_languages': ['en-US'],
    },
    {
      'source': '/messages/en-US/*.json',
      'translation': '/messages/%locale%/%original_file_name%',
      'exclude_target_languages': ['en-US'],
    },
  ]
