export const COMAPEO_BLUE = '#0066FF'
export const DARK_COMAPEO_BLUE = '#050F77'
export const LIGHT_COMAPEO_BLUE = '#CCE0FF'

export const CORNFLOWER_BLUE = '#80A0FF'
export const DARK_BLUE = '#000033'
export const BLUE_GREY = '#CCCCD6'
export const DARK_GREY = '#757575'
export const LIGHT_GREY = '#ededed'

export const ORANGE = '#FF9933'
export const DARK_ORANGE = '#E86826'
export const DARKER_ORANGE = '#D95F28'

export const GREEN = '#59A553'
export const RED = '#D92222'
export const BLACK = '#000000'
export const ALMOST_BLACK = '#333333'
export const WHITE = '#ffffff'

export const PROJECT_ORANGE = '#FFF5EB'
export const PROJECT_BLUE = '#E5F0FF'
export const PROJECT_GREEN = '#EEF6EE'
export const PROJECT_RED = '#FBE9E9'
export const PROJECT_GREY = '#E5E5EB'
