// This file is generated by icon spritesheet generator

export const iconNames = [
	'openmoji-wrench',
	'openmoji-world-map',
	'openmoji-red-circle',
	'openmoji-raised-hand-medium-skin-tone',
	'openmoji-raised-fist-medium-skin-tone',
	'openmoji-locked-with-key',
	'openmoji-handshake-medium-skin-tone',
	'openmoji-bust-in-silhouette',
	'openmoji-bar-chart',
	'material-symbols-new-window',
	'material-symbols-encrypted-weight400',
	'material-symbols-encrypted-weight200',
	'material-symbols-computer',
	'material-settings',
	'material-person-add',
	'material-offline-bolt',
	'material-hiking',
	'material-expand-more',
	'material-expand-less',
	'material-error-outline',
	'material-check-circle',
	'material-bolt',
	'material-arrow-back',
	'comapeo-cards',
] as const

export type IconName = (typeof iconNames)[number]
