# Summary:
#
# Publishes a release when a release version tag is created.
#
# Triggers:
#
# - Creating a new release tag (tag starting with `v`)
name: Build Production

on:
  push:
    tags:
      # "Release" version tags (i.e. prefixed with `v`) are only created through our automations (see ./tag-release.yml)
      - 'v*'

jobs:
  release:
    uses: ./.github/workflows/create-builds.yml
    with:
      app_type: 'production'
      build_sha: ${{ github.sha }}
    secrets: inherit
