# Summary:
#
# Reusable workflow for creating and uploading compiled translations.
# formatjs tooling no longer supports macOS x64 so we compile the translations as a separate
# job that gets used by other jobs (https://github.com/digidem/comapeo-desktop/issues/592).
name: Compile translations

on:
  workflow_call:
    inputs:
      commit_sha:
        description: 'SHA of commit to use'
        type: string
    outputs:
      artifact_id:
        description: ID of uploaded artifact containing compiled translations
        value: ${{ jobs.compile.outputs.artifact_id }}

env:
  COMMIT_SHA: ${{ inputs.commit_sha || github.sha }}

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      artifact_id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ env.COMMIT_SHA }}

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Update npm version
        uses: ./.github/update-npm-version

      - name: Install deps
        run: npm ci

      - name: Ensure intl outputs are up-to-date
        run: |
          node --run intl:extract
          node --run intl:generate
          git diff --exit-code

      - name: Compile translations
        run: node --run intl:compile

      - name: Upload compiled translations
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: translations-${{ github.sha }}
          path: translations/
          overwrite: true
          if-no-files-found: error
          retention-days: 30
